<?php
/**
 * Pure-PHP database backup.
 *
 * Deliberately doesn't shell out to mysqldump: many shared hosting plans
 * disable shell_exec()/exec() entirely, so a backup feature that depends
 * on it would silently fail there. This generates an equivalent .sql
 * dump directly through the existing mysqli connection instead — slower
 * for huge databases, but this project's tables are small, and it works
 * everywhere.
 */

const BACKUP_DIR = __DIR__ . '/../backups';

function ensure_backup_dir(): void
{
    if (!is_dir(BACKUP_DIR)) {
        mkdir(BACKUP_DIR, 0755, true);
    }
    $htaccess = BACKUP_DIR . '/.htaccess';
    if (!is_file($htaccess)) {
        file_put_contents($htaccess, "Require all denied\n");
    }
    $indexFile = BACKUP_DIR . '/index.php';
    if (!is_file($indexFile)) {
        file_put_contents($indexFile, "<?php http_response_code(403); exit('Forbidden');\n");
    }
}

/**
 * Generate a full SQL dump of the current database and save it to
 * /backups/backup_YYYY-MM-DD_HH-ii-ss.sql. Returns the filename on success.
 */
function generate_database_backup($conn, string $databaseName): ?string
{
    ensure_backup_dir();

    $filename = 'backup_' . date('Y-m-d_H-i-s') . '.sql';
    $path = BACKUP_DIR . '/' . $filename;
    $fh = fopen($path, 'w');
    if (!$fh) return null;

    fwrite($fh, "-- Database backup for `{$databaseName}`\n");
    fwrite($fh, "-- Generated: " . date('Y-m-d H:i:s') . "\n");
    fwrite($fh, "-- Generated by the admin panel's built-in backup tool\n\n");
    fwrite($fh, "SET FOREIGN_KEY_CHECKS=0;\n\n");

    $tablesResult = mysqli_query($conn, "SHOW TABLES");
    $tables = [];
    while ($row = mysqli_fetch_array($tablesResult, MYSQLI_NUM)) {
        $tables[] = $row[0];
    }

    foreach ($tables as $table) {
        // Structure
        $createRes = mysqli_query($conn, "SHOW CREATE TABLE `$table`");
        $createRow = mysqli_fetch_assoc($createRes);
        fwrite($fh, "-- --------------------------------------------------------\n");
        fwrite($fh, "-- Table: $table\n");
        fwrite($fh, "-- --------------------------------------------------------\n");
        fwrite($fh, "DROP TABLE IF EXISTS `$table`;\n");
        fwrite($fh, $createRow['Create Table'] . ";\n\n");

        // Data
        $dataRes = mysqli_query($conn, "SELECT * FROM `$table`");
        $numFields = mysqli_num_fields($dataRes);
        $fieldNames = [];
        while ($field = mysqli_fetch_field($dataRes)) {
            $fieldNames[] = '`' . $field->name . '`';
        }

        $rowCount = mysqli_num_rows($dataRes);
        if ($rowCount > 0) {
            fwrite($fh, "INSERT INTO `$table` (" . implode(', ', $fieldNames) . ") VALUES\n");
            $rowIndex = 0;
            while ($row = mysqli_fetch_row($dataRes)) {
                $rowIndex++;
                $escapedValues = array_map(function ($val) use ($conn) {
                    if ($val === null) return 'NULL';
                    return "'" . mysqli_real_escape_string($conn, $val) . "'";
                }, $row);
                fwrite($fh, '(' . implode(', ', $escapedValues) . ')');
                fwrite($fh, $rowIndex < $rowCount ? ",\n" : ";\n");
            }
        }
        fwrite($fh, "\n");
    }

    fwrite($fh, "SET FOREIGN_KEY_CHECKS=1;\n");
    fclose($fh);

    return $filename;
}

/** List existing backup files, newest first. */
function list_database_backups(): array
{
    ensure_backup_dir();
    $files = glob(BACKUP_DIR . '/backup_*.sql');
    $backups = [];
    foreach ($files as $file) {
        $backups[] = [
            'filename' => basename($file),
            'size' => filesize($file),
            'created_at' => filemtime($file),
        ];
    }
    usort($backups, fn($a, $b) => $b['created_at'] <=> $a['created_at']);
    return $backups;
}

function delete_database_backup(string $filename): bool
{
    // Only allow deleting files matching our exact naming pattern, inside our own backup dir
    if (!preg_match('/^backup_[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{2}-[0-9]{2}-[0-9]{2}\.sql$/', $filename)) {
        return false;
    }
    $path = BACKUP_DIR . '/' . $filename;
    return is_file($path) && unlink($path);
}

/** Keep only the N most recent backups (call after generating a new one). */
function prune_old_backups(int $keep = 10): void
{
    $backups = list_database_backups();
    foreach (array_slice($backups, $keep) as $old) {
        delete_database_backup($old['filename']);
    }
}
